### ISSUE TITLE
Carbon Wallet - extension

### ISSUE THREAD

**Issue by mayone** [Alpha-Carbon/wallet-extension#1]
## Summary
 
- We create our own wallet extension in order to add our own features to it
- Below is the TODO list and estimated scores of each items

## UI 
 
- [x] Create/Import wallet flow (800)
- [x] unlock (40)
- [x] Switch network (40)
- [ ] Create/Import account (160)
- [x] Account menu (40)
- [x] Account overview (240)
- [ ] Account detail (80)
    - [ ] Export private key
- [x] Sending flow (1120)
- [ ] Receive page (80)
- [ ] Assets (80)
- [ ] Activity (240)
    - [ ] Tx detail
- [ ] Settings (800)
    - [ ] General
    - [ ] Advanced
    - [ ] Contacts
    - [ ] Security
    - [ ] Alerts
    - [ ] Networks
    - [ ] Experimental
    - [ ] About
- [ ] Connect wallet

## Features
- [ ] Support transaction without gas
- [ ] Auto-sign in a period of time

____
